name: Haloo maailma!

on:
  push:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
  another_job:
    steps:
      - name: Sano haloo
        run: |
          echo "Haloo maailma!"